sonar.projectKey=vite-project
sonar.projectName=vite-project
sonar.projectVersion=0.0.0
sonar.sourceEncoding=UTF-8
sonar.language=ts
sonar.sources=src
sonar.tests=src
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,.git/**,.env,*.config.js,*.min.js,*.bundle.js
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info