name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unit Testing
        run: echo "Running Unit Testing"
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Image Build
        run: echo "Running Docker Image Build"

  docker-registry-push:
    needs: [unit-testing, docker-image-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Registry Push
        run: echo "Running Docker Registry Push"

