name: Main Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::130705418859:role/ajeetsingh-ec2-full-access-role
          aws-region: ap-south-1
          audience: sts.amazonaws.com
          
      - name: Login to Amazon ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV
          REPO_URI=${ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com
          echo "REPO_URI=$REPO_URI" >> $GITHUB_ENV
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPO_URI
      - name: Create ECR repository
        run: |
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          if ! aws ecr describe-repositories --region ap-south-1 --repository-names $REPO_NAME 2>/dev/null; then
            aws ecr create-repository --region ap-south-1 --repository-name $REPO_NAME
          fi
      - name: Build and push Docker image
        run: |
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          docker build -t $REPO_NAME .
          docker tag $REPO_NAME:latest $REPO_URI/$REPO_NAME:latest
          docker tag $REPO_NAME:latest $REPO_URI/$REPO_NAME:${GITHUB_SHA:0:7}
          docker push $REPO_URI/$REPO_NAME:latest
          docker push $REPO_URI/$REPO_NAME:${GITHUB_SHA:0:7}
      - name: Verify deployment
        run: |
          docker images
          echo "Deployment successful"
